GET http://127.0.0.1:8000/health/

###

POST http://127.0.0.1:8000/agent/invoke/
Content-Type: application/json

{
    "input": {
        "query": "Hola, me llamo Dairo"
    }
}

###
# @prompt thread_id
GET http://127.0.0.1:8000/agent/state/{{thread_id}}
Content-Type: application/json

###

GET http://127.0.0.1:8000/memories/
