line-length = 88
target-version = "py313"

[format]
quote-style = "single"
skip-magic-trailing-comma = false

[lint]
select = ["ALL"]
ignore = [
    "ANN002",  # Missing type annotation for `*args`
    "ANN003",  # Missing type annotation for `**kwargs`
    "ANN401",  # typing.Any is disallowed
    "B008",    # Do not perform function calls in argument defaults
    "BLE001",  # Do not catch blind exception: `Exception`
    "COM812",  # Trailing comma missing
    "D",       # pydocstyle
    "E402",    # Module level import not at top of file
    "E501",    # Line too long
    "EM101",   # Exception must not use a string literal
    "EM102",   # Exception must not use an f-string literal
    "FA100",   # Add `from __future__ import annotations`
    "FA102",   # Missing `from __future__ import annotations`
    "FBT001",  # Boolean-typed positional argument in function definition
    "FBT002",  # Boolean default positional argument in function definition
    "FIX001",  # Line contains FIXME, consider resolving the issue
    "FIX002",  # Line contains TODO, consider resolving the issue
    "N805",    # First argument of a method should be named `self`
    "PERF203", # try-except within a loop incurs performance overhead
    "PGH003",  # Use specific rule codes when ignoring type issues
    "PLR0913", # Too many arguments in function definition
    "S104",    # Possible binding to all interfaces
    "RUF012",  # Mutable class attributes should be annotated with `typing.ClassVar`
    "TD002",   # Missing author in TODO
    "TD003",   # Missing issue link for this TODO
    "TRY003",  # Avoid specifying long messages outside the exception class
]

[lint.per-file-ignores]
"tests/*" = [
    "ANN201", # Missing type annotation for public function
    "INP001", # File is part of an implicit namespace package, but does not include an `__init__.py` file
    "S101",   # Use of `assert` detected
]

[lint.flake8-quotes]
inline-quotes = "single"
