"""Utility functions for handling errors in the RFC 9457 format."""

from collections.abc import Sequence

from fastapi import Response
from pydantic import BaseModel, Field
from pydantic_core import ErrorDetails

from core.errors import Error


class ValidationErrorDetail(BaseModel):
    """Represents a single validation error detail in the RFC 9457 format."""

    detail: str = Field(..., description='A human-readable explanation of the error.')
    pointer: str = Field(
        ...,
        description='A JSON Pointer to the part of the request that caused the error.',
    )


class RFC9457Error(BaseModel):
    """Represents an error response in the RFC 9457 format."""

    type: str = Field(
        ..., description='A URI reference that identifies the problem type.'
    )
    title: str = Field(
        ..., description='A short, human-readable summary of the problem type.'
    )
    status: int = Field(
        ...,
        description='The HTTP status code generated by the origin server for this error.',
    )
    detail: str = Field(
        ...,
        description='A human-readable explanation specific to this occurrence of the problem.',
    )
    instance: str | None = Field(
        default=None,
        description='A URI reference that identifies the specific occurrence of the problem.',
    )
    code: str = Field(
        ...,
        description='A machine-readable error code that identifies the specific error.',
    )
    errors: list[ValidationErrorDetail] | None = Field(
        default=None,
        description='A list of validation error details, if applicable.',
    )


def pydantic_loc_to_json_pointer(loc: tuple[int | str, ...]) -> str:
    """Convert a Pydantic location to a JSON Pointer.

    Args:
        loc: A tuple representing the location of the error in the Pydantic model.

    Returns:
        A string representing the JSON Pointer corresponding to the Pydantic location.
    """
    return f'#/{"/".join(str(step) for step in loc)}'


def map_error_details(
    errors: Sequence[ValidationErrorDetail | ErrorDetails],
) -> list[ValidationErrorDetail]:
    """Map validation error details to a list of ValidationErrorDetail objects.

    Args:
        errors: A sequence of validation error details which can be either
            ValidationErrorDetail or ErrorDetails from Pydantic.

    Returns:
        A list of ValidationErrorDetail objects.
    """
    members = []

    for err in errors:
        if isinstance(err, ValidationErrorDetail):
            members.append(err)
        else:
            pointer = pydantic_loc_to_json_pointer(err['loc'])
            members.append(ValidationErrorDetail(detail=err['msg'], pointer=pointer))

    return members


def build_rfc_9457_fastapi_response(
    title: str,
    status: int,
    detail: str,
    code: str,
    instance: str | None = None,
    type_: str = 'about:blank',
    errors: Sequence[ValidationErrorDetail | ErrorDetails] | None = None,
    headers: dict[str, str] | None = None,
) -> Response:
    """Build a FastAPI Response object that conforms to the RFC 9457 error format.

    Args:
        title: A short, human-readable summary of the problem type.
        status: The HTTP status code generated by the origin server for this error.
        detail: A human-readable explanation specific to this occurrence of the problem.
        code: A machine-readable error code that identifies the specific error.
        instance: A URI reference that identifies the specific occurrence
            of the problem. Defaults to None.
        type_: The type of the error. Defaults to 'about:blank'.
        errors: A list of validation error details, if applicable. Defaults to None.
        headers: A dictionary of additional headers to include in the response.
            Defaults to None.

    Returns:
        A FastAPI Response object with the RFC 9457-compliant error content.
    """
    content = RFC9457Error(
        type=type_,
        title=title,
        status=status,
        detail=detail,
        instance=instance,
        code=code,
        errors=map_error_details(errors) if errors else None,
    ).model_dump_json()
    return Response(
        content=content,
        status_code=status,
        headers=headers,
        media_type='application/json',
    )


def error_to_rfc_9457_response(
    error: Error,
    instance: str | None = None,
    headers: dict[str, str] | None = None,
) -> Response:
    """Convert an Error object to an RFC 9457-compliant error response.

    Args:
        error: An Error object containing the error details.
        instance: A URI reference that identifies the specific occurrence
            of the problem. Defaults to None.
        headers: A dictionary of additional headers to include in the response.
            Defaults to None.

    Returns:
        A Response object with the RFC 9457-compliant error content.
    """
    return build_rfc_9457_fastapi_response(
        title=error.title,
        status=error.status,
        detail=error.detail,
        code=error.code,
        type_=error.type,
        instance=instance,
        headers=headers,
    )
